/*
 * sara_face_led_driver_define.h
 *
 * Created: 2016-11-03 09:18:40
 *  Author: Salco
 */ 


#ifndef SARA_FACE_LED_DRIVER_DEFINE_H_
#define SARA_FACE_LED_DRIVER_DEFINE_H_

// Which pin on the Arduino is connected to the NeoPixels?
// On a Trinket or Gemma we suggest changing this to 1
#define PIN            6

// How many NeoPixels are attached to the Arduino?
#define NUMPIXELS   81
#define EYEPIXELS   14
#define BASE_BOUCHE EYEPIXELS*2

#define DEFAULT_BRIGHTNESS 75


#if defined(SOUND_WITH_AUDIO_IN)
  #define VOLT_MAX_MASK_BUFFER 2
  #define VOLT_CUR_MASK_BUFFER 2
  #define VOLT_MIN_MASK_BUFFER 2
  
  #define MAX_FRAME 6
  #define MAX_MOUTH_COL 11
  #define MOUTH_MAX_COL_SIZE { (1<<2),(1<<2),(1<<4),(1<<4),(1<<7),(1<<4),(1<<7),(1<<4),(1<<4),(1<<2),(1<<2) }
  const unsigned char mouthMaxColSize[] = MOUTH_MAX_COL_SIZE;
  #define DEFAULT_RED_LED_MOUTH 0
  #define DEFAULT_GREEN_LED_MOUTH 0
  #define DEFAULT_BLUE_LED_MOUTH 50
#endif


//organisation des led de la bouche
#define LED_MOUTH_COL_1_ROW_1 ((BASE_BOUCHE+0)+(MAX_MOUTH_COL*0))
#define LED_MOUTH_COL_1_ROW_2 ((BASE_BOUCHE+1)+(MAX_MOUTH_COL*0))
#define LED_MOUTH_COL_1_ROW_3 ((BASE_BOUCHE+2)+(MAX_MOUTH_COL*0))

#define LED_MOUTH_COL_2_ROW_1 ((BASE_BOUCHE+0)+(MAX_MOUTH_COL*1))
#define LED_MOUTH_COL_2_ROW_2 ((BASE_BOUCHE+1)+(MAX_MOUTH_COL*1))
#define LED_MOUTH_COL_2_ROW_3 ((BASE_BOUCHE+2)+(MAX_MOUTH_COL*1))

#define LED_MOUTH_COL_3_ROW_1 ((BASE_BOUCHE+0)+(MAX_MOUTH_COL*2))
#define LED_MOUTH_COL_3_ROW_2 ((BASE_BOUCHE+1)+(MAX_MOUTH_COL*2))
#define LED_MOUTH_COL_3_ROW_3 ((BASE_BOUCHE+2)+(MAX_MOUTH_COL*2))
#define LED_MOUTH_COL_3_ROW_4 ((BASE_BOUCHE+3)+(MAX_MOUTH_COL*2))
#define LED_MOUTH_COL_3_ROW_5 ((BASE_BOUCHE+4)+(MAX_MOUTH_COL*2))

#define LED_MOUTH_COL_4_ROW_1 ((BASE_BOUCHE+0)+(MAX_MOUTH_COL*3))
#define LED_MOUTH_COL_4_ROW_2 ((BASE_BOUCHE+1)+(MAX_MOUTH_COL*3))
#define LED_MOUTH_COL_4_ROW_3 ((BASE_BOUCHE+2)+(MAX_MOUTH_COL*3))
#define LED_MOUTH_COL_4_ROW_4 ((BASE_BOUCHE+3)+(MAX_MOUTH_COL*3))
#define LED_MOUTH_COL_4_ROW_5 ((BASE_BOUCHE+4)+(MAX_MOUTH_COL*3))

#define LED_MOUTH_COL_5_ROW_1 ((BASE_BOUCHE+0)+(MAX_MOUTH_COL*4))
#define LED_MOUTH_COL_5_ROW_2 ((BASE_BOUCHE+1)+(MAX_MOUTH_COL*4))
#define LED_MOUTH_COL_5_ROW_3 ((BASE_BOUCHE+2)+(MAX_MOUTH_COL*4))
#define LED_MOUTH_COL_5_ROW_4 ((BASE_BOUCHE+3)+(MAX_MOUTH_COL*4))
#define LED_MOUTH_COL_5_ROW_5 ((BASE_BOUCHE+4)+(MAX_MOUTH_COL*4))
#define LED_MOUTH_COL_5_ROW_6 ((BASE_BOUCHE+5)+(MAX_MOUTH_COL*4))
#define LED_MOUTH_COL_5_ROW_7 ((BASE_BOUCHE+6)+(MAX_MOUTH_COL*4))
#define LED_MOUTH_COL_5_ROW_8 ((BASE_BOUCHE+7)+(MAX_MOUTH_COL*4))

#define LED_MOUTH_COL_6_ROW_1 ((BASE_BOUCHE+0)+(MAX_MOUTH_COL*5))
#define LED_MOUTH_COL_6_ROW_2 ((BASE_BOUCHE+1)+(MAX_MOUTH_COL*5))
#define LED_MOUTH_COL_6_ROW_3 ((BASE_BOUCHE+2)+(MAX_MOUTH_COL*5))
#define LED_MOUTH_COL_6_ROW_4 ((BASE_BOUCHE+3)+(MAX_MOUTH_COL*5))
#define LED_MOUTH_COL_6_ROW_5 ((BASE_BOUCHE+4)+(MAX_MOUTH_COL*5))

#define LED_MOUTH_COL_7_ROW_1 ((BASE_BOUCHE+0)+(MAX_MOUTH_COL*6))
#define LED_MOUTH_COL_7_ROW_2 ((BASE_BOUCHE+1)+(MAX_MOUTH_COL*6))
#define LED_MOUTH_COL_7_ROW_3 ((BASE_BOUCHE+2)+(MAX_MOUTH_COL*6))
#define LED_MOUTH_COL_7_ROW_4 ((BASE_BOUCHE+3)+(MAX_MOUTH_COL*6))
#define LED_MOUTH_COL_7_ROW_5 ((BASE_BOUCHE+4)+(MAX_MOUTH_COL*6))
#define LED_MOUTH_COL_7_ROW_6 ((BASE_BOUCHE+5)+(MAX_MOUTH_COL*6))
#define LED_MOUTH_COL_7_ROW_7 ((BASE_BOUCHE+6)+(MAX_MOUTH_COL*6))
#define LED_MOUTH_COL_7_ROW_8 ((BASE_BOUCHE+7)+(MAX_MOUTH_COL*6))

#define LED_MOUTH_COL_8_ROW_1 ((BASE_BOUCHE+0)+(MAX_MOUTH_COL*7))
#define LED_MOUTH_COL_8_ROW_2 ((BASE_BOUCHE+1)+(MAX_MOUTH_COL*7))
#define LED_MOUTH_COL_8_ROW_3 ((BASE_BOUCHE+2)+(MAX_MOUTH_COL*7))
#define LED_MOUTH_COL_8_ROW_4 ((BASE_BOUCHE+3)+(MAX_MOUTH_COL*7))
#define LED_MOUTH_COL_8_ROW_5 ((BASE_BOUCHE+4)+(MAX_MOUTH_COL*7))

#define LED_MOUTH_COL_9_ROW_1 ((BASE_BOUCHE+0)+(MAX_MOUTH_COL*8))
#define LED_MOUTH_COL_9_ROW_2 ((BASE_BOUCHE+1)+(MAX_MOUTH_COL*8))
#define LED_MOUTH_COL_9_ROW_3 ((BASE_BOUCHE+2)+(MAX_MOUTH_COL*8))
#define LED_MOUTH_COL_9_ROW_4 ((BASE_BOUCHE+3)+(MAX_MOUTH_COL*8))
#define LED_MOUTH_COL_9_ROW_5 ((BASE_BOUCHE+4)+(MAX_MOUTH_COL*8))

#define LED_MOUTH_COL_10_ROW_1 ((BASE_BOUCHE+0)+(MAX_MOUTH_COL*9))
#define LED_MOUTH_COL_10_ROW_2 ((BASE_BOUCHE+1)+(MAX_MOUTH_COL*9))
#define LED_MOUTH_COL_10_ROW_3 ((BASE_BOUCHE+2)+(MAX_MOUTH_COL*9))

#define LED_MOUTH_COL_11_ROW_1 ((BASE_BOUCHE+0)+(MAX_MOUTH_COL*10))
#define LED_MOUTH_COL_11_ROW_2 ((BASE_BOUCHE+1)+(MAX_MOUTH_COL*10))
#define LED_MOUTH_COL_11_ROW_3 ((BASE_BOUCHE+2)+(MAX_MOUTH_COL*10))



#endif /* SARA_FACE_LED_DRIVER_DEFINE_H_ */
